import{assetUrl}from"../src/assetUrl";import test from"node:test";import a from"node:assert/strict";import{styles,concepts}from"../src/enhancedData";import{applyBudget,arrange,createProject,normalizeProject,progress,rank,refineConcept,remaining,replace,selected,swapItem,total,updateItem}from"../src/domain";const style=styles[0]!,c=concepts(style)[0]!;
test("generation progression reserves final stage",()=>{a.equal(progress(0).currentStage,0);a.equal(progress(28000).currentStage,6);a.equal(progress(5600,true).currentStage,7);a.equal(progress(31000).status,"delayed")});
test("totals and remaining derive from items",()=>{const x=c.shoppingItems.slice(0,2),sum=total(x);a.ok(sum>0);a.equal(remaining(updateItem(c,x[0]!.id,{isOwned:true}).shoppingItems.slice(0,2)),sum-x[0]!.unitPrice*x[0]!.quantity)});
test("swap preserves item id and category",()=>{const i=c.shoppingItems[0]!,n=swapItem(c,i.id,i.alternatives![0]!).shoppingItems[0]!;a.equal(n.id,i.id);a.equal(n.category,i.category)});
test("remove restore owned and purchased update totals",()=>{const i=c.shoppingItems[0]!,base=remaining(c.shoppingItems);for(const x of[{isRemoved:true},{isOwned:true},{isPurchased:true}])a.equal(remaining(updateItem(c,i.id,x).shoppingItems),base-i.unitPrice*i.quantity);a.equal(remaining(updateItem(updateItem(c,i.id,{isRemoved:true}),i.id,{isRemoved:false}).shoppingItems),base)});
test("priority and price ordering work",()=>{a.equal(arrange(c.shoppingItems)[0]!.category,"Finishes");const x=arrange(c.shoppingItems,"All","price-asc");a.ok(x[0]!.unitPrice<=x[1]!.unitPrice)});
test("alternatives rank supported dimensions",()=>{const x=rank([{id:"a",name:"a",retailer:"r",purchaseUrl:"u",unitPrice:10,difference:"x"},{id:"b",name:"b",retailer:"r",purchaseUrl:"u",unitPrice:20,difference:"x",available:true,dimensions:"20 in"}]);a.equal(x[0]!.id,"b")});
test("legacy defaults preserve old projects",()=>{const p=normalizeProject({concept:{id:"old",title:"Old",summary:"Saved",style:"Modern",palette:[],principles:[],shoppingItems:[{id:"i",name:"Item",category:"Decor",description:"",quantity:1,unitPrice:10,retailer:"R",purchaseUrl:"u"}]}});a.ok(p.concepts[0]!.designReport);a.ok(p.concepts[0]!.shoppingItems[0]!.rationale);a.equal(p.comparisonPosition,50)});
test("report includes every section",()=>{const r=c.designReport;a.ok(r.designDirection&&r.layoutAndCirculation&&r.colorAndMaterials&&r.lighting&&r.scaleAndProportion&&r.retainedElements&&r.priorityChanges&&r.designerNotes)});
test("concept selection and edits persist",()=>{let p=createProject(style,[]);p={...p,selectedConceptId:p.concepts[1]!.id};p=replace(p,updateItem(selected(p)!,selected(p)!.shoppingItems[0]!.id,{quantity:3}));const n=normalizeProject(JSON.parse(JSON.stringify(p)));a.equal(selected(n)!.id,p.concepts[1]!.id);a.equal(selected(n)!.shoppingItems[0]!.quantity,3)});test("generation progression exposes safe delayed and recoverable error fallbacks",()=>{const delayed=progress(31001,false);a.equal(delayed.status,"delayed");a.match(delayed.message??"",/taking a little longer/);const failed=progress(1400,false,"Network unavailable");a.equal(failed.status,"error");a.equal(failed.error,"Network unavailable");a.ok(failed.currentStage<7)});
test("refinement updates the rendered image and applies explicit shopping decisions",()=>{const revised=refineConcept(c,"http://localhost:8787/designs/revised.jpg","Lighter palette",["keep-sofa","exclude-art","lower-price"]);a.ok(revised.imageDataUrl?.includes("/designs/revised.jpg"));a.equal(revised.revisionNotes?.[revised.revisionNotes.length-1],"Lighter palette");a.equal(revised.shoppingItems.find(i=>i.name.toLowerCase().includes("sofa"))?.isOwned,true);a.equal(revised.shoppingItems.find(i=>i.name.toLowerCase().includes("art"))?.isRemoved,true)});
test("older secondary concepts inherit the primary image instead of rendering blank",()=>{const p=normalizeProject({concepts:[{...c,imageDataUrl:"http://localhost:8787/designs/primary.jpg"},{...concepts(style)[1]!,imageDataUrl:undefined}]});a.equal(p.concepts[1]?.imageDataUrl,p.concepts[0]?.imageDataUrl);a.equal(p.concepts[1]?.generationStatus,"partial")});

test("saved localhost design URLs are rewritten to the phone-reachable API",()=>{a.equal(assetUrl("http://localhost:3201/designs/example.jpg","http://192.168.4.46:3201"),"http://192.168.4.46:3201/designs/example.jpg")});

test("budget selection stays scoped to the selected concept",()=>{let p=createProject(style,[]);p={...p,selectedConceptId:p.concepts[1]!.id,approvedConceptId:p.concepts[1]!.id};const other=p.concepts[0]!.shoppingItems[0]!.name;const budgeted=applyBudget(p,"save");a.equal(budgeted.budgetTier,"save");a.equal(budgeted.concepts[0]!.shoppingItems[0]!.name,other);a.equal(selected(budgeted)!.id,p.concepts[1]!.id)});
test("project lifecycle collections survive normalization",()=>{const p=createProject(style,[]);const raw={...p,fieldFinds:[{id:"f",image:{uri:"item.jpg"},notes:"chair",verdict:"fits" as const,advice:"Works",createdAt:p.updatedAt}],progressUpdates:[{id:"u",image:{uri:"room.jpg"},note:"painted",guidance:"Keep going",createdAt:p.updatedAt}],reminders:["Measure"],deals:[{id:"d",itemId:"i",title:"Sale",retailer:"Shop",price:8,originalPrice:10,url:"https://example.com",checkedAt:p.updatedAt}]};const n=normalizeProject(raw);a.equal(n.fieldFinds[0]!.notes,"chair");a.equal(n.progressUpdates[0]!.note,"painted");a.equal(n.deals[0]!.price,8)});
test("budget choices stay tied to the room item and can return to the original",()=>{const p=createProject(style,[]),original=selected(p)!.shoppingItems[0]!,saved=applyBudget(p,"save"),savedItem=selected(saved)!.shoppingItems[0]!;a.ok(savedItem.unitPrice<=original.unitPrice);a.equal(savedItem.category,original.category);const invested=applyBudget(saved,"invest"),restored=selected(invested)!.shoppingItems[0]!;a.equal(restored.name,original.name);a.equal(restored.unitPrice,original.unitPrice);a.equal(invested.budgetTier,"invest")});
test("budget selection uses verified retailer tiers instead of price multipliers",()=>{const p=createProject(style,[]),concept=selected(p)!,item=concept.shoppingItems[0]!,checkedAt="2026-07-27T12:00:00.000Z",balanced={name:"Balanced room chair",retailer:"Wayfair",purchaseUrl:"https://www.wayfair.com/furniture/pdp/balanced-room-chair-w123.html",unitPrice:320,dimensions:"30 in",finish:"Oak",rationale:"Balanced fit",availability:"In stock",priceStatus:"verified" as const,lastPriceCheckedAt:checkedAt,budgetTier:"balanced" as const},seeded=replace(p,{...concept,shoppingItems:[{...item,...balanced,originalSelection:balanced,alternatives:[{id:"save",name:"Save room chair",retailer:"Walmart",purchaseUrl:"https://www.walmart.com/ip/123456",unitPrice:180,difference:"Save tier",priceStatus:"verified",lastPriceCheckedAt:checkedAt,budgetTier:"save"},{id:"invest",name:"Invest room chair",retailer:"Home Depot",purchaseUrl:"https://www.homedepot.com/p/123456789",unitPrice:590,difference:"Invest tier",priceStatus:"verified",lastPriceCheckedAt:checkedAt,budgetTier:"invest"},{id:"bad",name:"Category result",retailer:"Home Depot",purchaseUrl:"https://www.homedepot.com/b/Furniture/N-123",unitPrice:90,difference:"Invalid link",priceStatus:"verified",lastPriceCheckedAt:checkedAt,budgetTier:"save"}]},...concept.shoppingItems.slice(1)]});const saved=applyBudget(seeded,"save"),balancedProject=applyBudget(saved,"balanced"),invested=applyBudget(balancedProject,"invest");a.equal(selected(saved)!.shoppingItems[0]!.name,"Save room chair");a.equal(selected(balancedProject)!.shoppingItems[0]!.name,"Balanced room chair");a.equal(selected(invested)!.shoppingItems[0]!.name,"Invest room chair");for(const project of[saved,balancedProject,invested]){const chosen=selected(project)!.shoppingItems[0]!;a.equal(chosen.priceStatus,"verified");a.equal(chosen.lastPriceCheckedAt,checkedAt);a.match(chosen.purchaseUrl,/^https:\/\/www\./)}});

const seededNames=new Set(concepts(style)[0]!.shoppingItems.map(i=>i.name));
test("a live generation that resolved no products yields an empty plan on every concept, never seeded products",()=>{const legacy={id:"server",title:"Signature",summary:"Grounded",style:"Modern",palette:[],principles:[],shoppingItems:[],variants:[{conceptName:"Refined" as const,generationStatus:"complete" as const},{conceptName:"Expressive" as const,generationStatus:"complete" as const}]};const p=createProject(style,[{uri:"before"}],legacy as never);a.equal(p.concepts.length,3);for(const c of p.concepts){a.equal(c.shoppingItems.length,0,c.conceptName+" must not fall back to seeded products");a.equal(total(c.shoppingItems),0)}});
test("live server products reach every concept identically and keep concept-scoped ids",()=>{const item={id:"server-0",name:"Fielding linen sofa",category:"Furniture",description:"Scaled to the photographed wall",quantity:1,unitPrice:1299,retailer:"West Elm",purchaseUrl:"https://www.westelm.com/products/fielding-sofa-h1234/",priceStatus:"verified" as const};const legacy={id:"server",title:"Signature",summary:"Grounded",style:"Modern",palette:[],principles:[],shoppingItems:[item],variants:[{conceptName:"Refined" as const,generationStatus:"complete" as const},{conceptName:"Expressive" as const,generationStatus:"complete" as const}]};const p=createProject(style,[{uri:"before"}],legacy as never);for(const c of p.concepts){a.equal(c.shoppingItems.length,1);a.equal(c.shoppingItems[0]!.name,"Fielding linen sofa");a.equal(c.shoppingItems[0]!.conceptId,c.id);a.equal(c.shoppingItems[0]!.id,c.id+"-room-0");a.ok(!seededNames.has(c.shoppingItems[0]!.name))}});
test("no seeded product can reach a project created from a server response",()=>{for(const items of[[],[{id:"s",name:"Fielding linen sofa",category:"Furniture",description:"d",quantity:1,unitPrice:10,retailer:"R",purchaseUrl:"https://www.westelm.com/products/x-1/"}]]){const p=createProject(style,[],{id:"server",title:"T",summary:"S",style:"Modern",palette:[],principles:[],shoppingItems:items} as never);for(const c of p.concepts)for(const i of c.shoppingItems)a.ok(!seededNames.has(i.name),"seeded product "+i.name+" leaked into a live project")}});
test("demo projects still receive seeded sample products",()=>{const p=createProject(style,[]);a.ok(p.concepts.every(c=>c.shoppingItems.length>0));a.ok(seededNames.has(selected(p)!.shoppingItems[0]!.name))});
