import{assetUrl}from"../src/assetUrl";import test from"node:test";import a from"node:assert/strict";import{styles,concepts}from"../src/enhancedData";import{arrange,createProject,normalizeProject,progress,rank,refineConcept,remaining,replace,selected,swapItem,total,updateItem}from"../src/domain";const style=styles[0]!,c=concepts(style)[0]!;
test("generation progression reserves final stage",()=>{a.equal(progress(0).currentStage,0);a.equal(progress(28000).currentStage,6);a.equal(progress(5600,true).currentStage,7);a.equal(progress(31000).status,"delayed")});
test("totals and remaining derive from items",()=>{const x=c.shoppingItems.slice(0,2),sum=total(x);a.ok(sum>0);a.equal(remaining(updateItem(c,x[0]!.id,{isOwned:true}).shoppingItems.slice(0,2)),sum-x[0]!.unitPrice*x[0]!.quantity)});
test("swap preserves item id and category",()=>{const i=c.shoppingItems[0]!,n=swapItem(c,i.id,i.alternatives![0]!).shoppingItems[0]!;a.equal(n.id,i.id);a.equal(n.category,i.category)});
test("remove restore owned and purchased update totals",()=>{const i=c.shoppingItems[0]!,base=remaining(c.shoppingItems);for(const x of[{isRemoved:true},{isOwned:true},{isPurchased:true}])a.equal(remaining(updateItem(c,i.id,x).shoppingItems),base-i.unitPrice*i.quantity);a.equal(remaining(updateItem(updateItem(c,i.id,{isRemoved:true}),i.id,{isRemoved:false}).shoppingItems),base)});
test("priority and price ordering work",()=>{a.equal(arrange(c.shoppingItems)[0]!.category,"Finishes");const x=arrange(c.shoppingItems,"All","price-asc");a.ok(x[0]!.unitPrice<=x[1]!.unitPrice)});
test("alternatives rank supported dimensions",()=>{const x=rank([{id:"a",name:"a",retailer:"r",purchaseUrl:"u",unitPrice:10,difference:"x"},{id:"b",name:"b",retailer:"r",purchaseUrl:"u",unitPrice:20,difference:"x",available:true,dimensions:"20 in"}]);a.equal(x[0]!.id,"b")});
test("legacy defaults preserve old projects",()=>{const p=normalizeProject({concept:{id:"old",title:"Old",summary:"Saved",style:"Modern",palette:[],principles:[],shoppingItems:[{id:"i",name:"Item",category:"Decor",description:"",quantity:1,unitPrice:10,retailer:"R",purchaseUrl:"u"}]}});a.ok(p.concepts[0]!.designReport);a.ok(p.concepts[0]!.shoppingItems[0]!.rationale);a.equal(p.comparisonPosition,50)});
test("report includes every section",()=>{const r=c.designReport;a.ok(r.designDirection&&r.layoutAndCirculation&&r.colorAndMaterials&&r.lighting&&r.scaleAndProportion&&r.retainedElements&&r.priorityChanges&&r.designerNotes)});
test("concept selection and edits persist",()=>{let p=createProject(style,[]);p={...p,selectedConceptId:p.concepts[1]!.id};p=replace(p,updateItem(selected(p)!,selected(p)!.shoppingItems[0]!.id,{quantity:3}));const n=normalizeProject(JSON.parse(JSON.stringify(p)));a.equal(selected(n)!.id,p.concepts[1]!.id);a.equal(selected(n)!.shoppingItems[0]!.quantity,3)});test("generation progression exposes safe delayed and recoverable error fallbacks",()=>{const delayed=progress(31001,false);a.equal(delayed.status,"delayed");a.match(delayed.message??"",/taking a little longer/);const failed=progress(1400,false,"Network unavailable");a.equal(failed.status,"error");a.equal(failed.error,"Network unavailable");a.ok(failed.currentStage<7)});
test("refinement updates the rendered image and applies explicit shopping decisions",()=>{const revised=refineConcept(c,"http://localhost:8787/designs/revised.jpg","Lighter palette",["keep-sofa","exclude-art","lower-price"]);a.ok(revised.imageDataUrl?.includes("/designs/revised.jpg"));a.equal(revised.revisionNotes?.[revised.revisionNotes.length-1],"Lighter palette");a.equal(revised.shoppingItems.find(i=>i.name.toLowerCase().includes("sofa"))?.isOwned,true);a.equal(revised.shoppingItems.find(i=>i.name.toLowerCase().includes("art"))?.isRemoved,true)});
test("older secondary concepts inherit the primary image instead of rendering blank",()=>{const p=normalizeProject({concepts:[{...c,imageDataUrl:"http://localhost:8787/designs/primary.jpg"},{...concepts(style)[1]!,imageDataUrl:undefined}]});a.equal(p.concepts[1]?.imageDataUrl,p.concepts[0]?.imageDataUrl);a.equal(p.concepts[1]?.generationStatus,"partial")});

test("saved localhost design URLs are rewritten to the phone-reachable API",()=>{a.equal(assetUrl("http://localhost:8787/designs/example.jpg","http://192.168.4.46:8787"),"http://192.168.4.46:8787/designs/example.jpg")});
