import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{styles,concepts}from"../src/enhancedData";import{createProject,normalizeProject,resolveProjectConflict,selected,updateItem}from"../src/domain";import{featureFlags}from"../src/featureFlags";import type{Event}from"../src/analytics";
import{isDirectProductUrl}from"../src/productLinks";
const style=styles[0]!;
test("server variants populate three independent concepts",()=>{const base=concepts(style),legacy={id:"server",title:"Signature",summary:"Grounded",style:"Modern",palette:[],principles:[],shoppingItems:[],beforeImageUrl:"before",imageDataUrl:"signature",designReport:base[0]!.designReport,roomAnalysis:{roomType:"living room",proportions:"wide",focalPoints:["window"],lighting:"right daylight",retainedElements:["window"],circulation:"open",confidence:"high"},variants:[{conceptName:"Refined" as const,imageDataUrl:"refined",designReport:base[1]!.designReport,generationStatus:"complete" as const},{conceptName:"Expressive" as const,imageDataUrl:"expressive",designReport:base[2]!.designReport,generationStatus:"complete" as const}]};const project=createProject(style,[{uri:"before"}],legacy as never);assert.equal(project.concepts.length,3);assert.equal(project.concepts[0]!.imageDataUrl,"signature");assert.equal(project.concepts[1]!.imageDataUrl,"refined");assert.equal(project.concepts[2]!.imageDataUrl,"expressive");assert.ok(project.concepts.every(c=>c.shoppingItems.every(i=>i.conceptId===c.id)))});
test("partial variant failure preserves usable primary and fallbacks",()=>{const project=createProject(style,[],{id:"server",title:"Signature",summary:"Grounded",style:"Modern",palette:[],principles:[],shoppingItems:[],variants:[{conceptName:"Refined",generationStatus:"failed"}]} as never);assert.equal(project.concepts.length,3);assert.equal(selected(project)!.conceptName,"Signature");assert.ok(project.concepts[1]!.designReport)});
test("conflicts preserve the latest item action",()=>{let local=createProject(style,[]),server=normalizeProject(JSON.parse(JSON.stringify(local)));const item=selected(local)!.shoppingItems[0]!;local={...local,updatedAt:"2026-01-01T00:00:01.000Z",concepts:[updateItem(selected(local)!,item.id,{quantity:4}),...local.concepts.slice(1)]};server={...server,updatedAt:"2026-01-01T00:00:02.000Z"};const merged=resolveProjectConflict(local,server);assert.equal(selected(merged)!.shoppingItems[0]!.quantity,4)});
test("all required feature flags remain enabled by default",()=>{assert.equal(Object.keys(featureFlags).length,7);assert.ok(Object.values(featureFlags).every(Boolean))});
test("every required analytics event is wired in active UI",()=>{const required:Event[]=["room_scan_started","room_scan_completed","style_selected","concept_generation_started","generation_stage_viewed","concept_generation_completed","concept_generation_failed","concept_viewed","concept_selected","before_after_opened","before_after_shared","design_report_opened","design_report_section_expanded","shopping_item_opened","product_rationale_opened","retailer_link_opened","alternatives_opened","product_swapped","product_swap_undone","item_marked_owned","item_marked_purchased","item_removed","item_restored","shopping_plan_sorted","shopping_plan_filtered","project_shared"];const source=readFileSync("src/RoomMuseApp.tsx","utf8")+readFileSync("src/EnhancedScreens.tsx","utf8");for(const event of required)assert.ok(source.includes('"'+event+'"'))});
test("legacy concept still normalizes without enhanced fields",()=>{const p=normalizeProject({concept:{id:"old",title:"Old",summary:"Saved",style:"Modern",palette:[],principles:[],shoppingItems:[]}});assert.equal(p.concepts[0]!.conceptName,"Signature");assert.ok(p.concepts[0]!.designReport);assert.equal(p.comparisonPosition,50)});
test("room-grounded server items propagate to every generated concept",()=>{const base=concepts(style),roomItem={id:"server-room-0",name:"Compact reading chair",category:"Furniture",description:"Fits the photographed reading corner",quantity:1,unitPrice:420,retailer:"Wayfair",purchaseUrl:"https://example.com/chair",rationale:"Grounded in the photographed reading corner"};const legacy={id:"server",title:"Signature",summary:"Grounded",style:"Modern",palette:[],principles:[],shoppingItems:[roomItem],designReport:base[0]!.designReport,variants:[{conceptName:"Refined" as const,generationStatus:"complete" as const},{conceptName:"Expressive" as const,generationStatus:"complete" as const}]};const project=createProject(style,[{uri:"before"}],legacy as never);for(const concept of project.concepts){assert.equal(concept.shoppingItems.length,1);assert.equal(concept.shoppingItems[0]!.name,"Compact reading chair");assert.equal(concept.shoppingItems[0]!.conceptId,concept.id);assert.match(concept.shoppingItems[0]!.rationale??"",/photographed reading corner/)}});
test("product links reject search and category pages",()=>{assert.equal(isDirectProductUrl("https://www.wayfair.com/keyword.php?keyword=chair"),false);assert.equal(isDirectProductUrl("https://www.homedepot.com/s/lamp"),false);assert.equal(isDirectProductUrl("https://www.homedepot.com/b/Furniture-Dining-Chairs/N-123"),false);assert.equal(isDirectProductUrl("https://www.homedepot.com/p/337648850"),true);assert.equal(isDirectProductUrl("https://www.walmart.com/ip/5143607705"),true);assert.equal(isDirectProductUrl("https://www.example.com/products/oak-chair-123"),true);assert.equal(isDirectProductUrl("http://www.example.com/products/chair"),false)});
test("video capture requests microphone access and includes an in-app permission back button",()=>{const camera=readFileSync("src/EnhancedScreens.tsx","utf8");const app=readFileSync("app.json","utf8");assert.match(camera,/useMicrophonePermissions/);assert.match(camera,/await allowMicrophone/);assert.match(camera,/MediaRecorder/);assert.match(camera,/recordWeb/);assert.match(camera,/webVideoFrame/);assert.doesNotMatch(camera,/mode=\{captureMode\} mute/);assert.match(camera,/permission\??\.granted\).*accessibilityLabel="Go back"/);assert.match(app,/NSMicrophoneUsageDescription/);assert.match(app,/microphonePermission/)});
test("system back stays inside RoomMuse",()=>{const source=readFileSync("src/RoomMuseApp.tsx","utf8");assert.match(source,/BackHandler\.addEventListener\("hardwareBackPress"/);assert.match(source,/addEventListener\("popstate"/);assert.match(source,/deals:"project"/);assert.match(source,/capture:"home"/)});
test("retailer data uses live web search and never fabricates links or discounts",()=>{const server=readFileSync("server/server.mjs","utf8");const deals=readFileSync("src/ProjectScreens.tsx","utf8");const domain=readFileSync("src/domain.ts","utf8");assert.match(server,/tools: \[\{ type: "web_search"/);assert.match(server,/model: productSearchModel/);assert.doesNotMatch(server,/api\.openai\.com\/v1\/chat\/completions/);assert.match(server,/const imageModel = process\.env\.OPENAI_IMAGE_MODEL \?\? "gpt-image-2"/);assert.match(server,/annotation\.type === "url_citation"/);assert.match(server,/Use ONLY these exact cited product URLs/);assert.match(server,/isAllowedRetailerSource\(url\)/);assert.match(server,/sourceUrls\.has\(sourceUrlKey\(product\.directUrl\)\)/);assert.match(server,/Promise\.all\(batches\.map\(batch\s*=>\s*resolveProductBatch\(batch, style, context\)\)\)/);assert.doesNotMatch(server,/mapWithConcurrency/);assert.doesNotMatch(server,/resolveProductChoices/);assert.match(server,/Promise\.all\(unmatched\.map\(entry\s*=>\s*resolveProductBatch\(\[entry\], style, context\)\)\)/);assert.match(server,/priceStatus: verified \? "verified" : "estimate"/);assert.match(server,/budgetTier: primary\?\.tier/);assert.match(server,/budgetTier: product\.tier/);assert.doesNotMatch(server,/wayfair\.com\/keyword/);assert.doesNotMatch(server,/homedepot\.com\/s\//);assert.match(server,/function planContext/);assert.match(server,/\$\{guidance\}/);assert.match(server,/provenance: verified \? "verified" : "generated"/);assert.match(server,/api\/shopping-plan/);assert.match(server,/api\/prices\/refresh/);assert.match(server,/api\/identify-product/);assert.match(server,/sourceUrlKey\(price\.url\) !== sourceUrlKey\(item\.purchaseUrl\)/);assert.match(server,/!cited\.has\(sourceUrlKey\(item\.purchaseUrl\)\)/);assert.match(server,/status === "complete"\) return send\(res, 409/);assert.match(server,/NEVER invent a measurement, a price, a brand, or a retailer/);assert.match(server,/dimensionsConfidence === "unknown" \? undefined/);assert.doesNotMatch(deals,/\.82\+n\*\.03/);assert.match(deals,/a\.priceStatus==="verified"/);assert.match(deals,/isDirectProductUrl\(a\.purchaseUrl\)/);assert.doesNotMatch(domain,/const factor=/);assert.match(domain,/a\.budgetTier===tier/);assert.match(domain,/isDirectProductUrl\(a\.purchaseUrl\)/)});

// Real product URLs observed from a live search on 2026-08-16. Every one of these must be
// accepted: the /^\/p\// pattern for Lamps Plus rejected its /products/ form, which silently
// dropped a verified product from the plan.
test("verified live product URLs are accepted",()=>{for(const url of[
  "https://www.homedepot.com/p/336343453",
  "https://www.target.com/p/-/A-1011806485",
  "https://www.walmart.com/ip/10981207219",
  "https://www.rugsusa.com/products/seed-ivory-natural-handwoven-jute-rug?variant=50093398655270",
  "https://www.lampsplus.com/p/dainolite-finley-60-inch-high-matte-black-modern-floor-lamp__6622h",
  "https://www.lampsplus.com/products/regency-hill-65-and-one-half-inch-leisa-sand-finish-modern-floor-lamp__273a9.html",
  // G6 additions, each taken from a real product page rather than assumed.
  "https://www.cb2.com/camden-101-white-performance-fabric-sofa/s104962",
  "https://www.cb2.com/faible-100-white-performance-deep-depth-fabric-sofa/s355885",
  "https://www.allmodern.com/furniture/pdp/allmodern-lisette-87-upholstered-sofa-a110020027.html",
  "https://www.allmodern.com/furniture/pdp/allmodern-component-ottoman-goms1032.html"
])assert.equal(isDirectProductUrl(url),true,"should accept "+url)});
// Widening a pattern must not let a category or search page through — that is the failure the
// gate exists to prevent, so the negative cases are pinned alongside the positive ones.
test("widened patterns still reject non-product pages",()=>{for(const url of[
  "https://www.lampsplus.com/products/",
  "https://www.lampsplus.com/search/?q=floor+lamp",
  "https://www.lampsplus.com/p/",
  "https://www.homedepot.com/b/Lighting-Lamps/N-5yc1vZc7oj",
  "https://www.target.com/c/furniture/-/N-5xtvd",
  "https://www.rugsusa.com/collections/jute-rugs",
  // A widened domain must not become a hole: these are the category and brand pages that live
  // alongside the product pages above.
  "https://www.cb2.com/furniture/sofas/1",
  "https://www.cb2.com/apartment-sofas",
  "https://www.cb2.com/furniture/living-room-furniture/",
  "https://www.allmodern.com/brand/bnd/allmodern-b56298.html",
  "https://www.allmodern.com/design-services"
])assert.equal(isDirectProductUrl(url),false,"should reject "+url)});
// The pattern table is duplicated between the Node server and the app, which cannot share a
// module. Drift would mean the server accepts a link the app then refuses to open, or worse.
test("server and client retailer pattern tables stay identical",()=>{const grab=(source:string)=>{const start=source.indexOf("retailerPatterns"),body=source.slice(start,source.indexOf("]",source.indexOf("crateandbarrel",start)+200));return body.replace(/\s|,$/g,"")};const server=readFileSync("server/server.mjs","utf8"),client=readFileSync("src/productLinks.ts","utf8");const clientBody=client.slice(client.indexOf("retailerProductPaths"),client.indexOf("];",client.indexOf("retailerProductPaths"))).replace(/\s|,$/g,"");for(const domain of["homedepot.com","lowes.com","target.com","walmart.com","ikea.com","wayfair.com","westelm.com","potterybarn.com","crateandbarrel.com","lampsplus.com","rugsusa.com"]){const pattern=(s:string)=>{const i=s.indexOf('"'+domain+'"');assert.ok(i>=0,domain+" missing");return s.slice(i+domain.length+2,s.indexOf("]",i))};assert.equal(pattern(grab(server)),pattern(clientBody),"pattern drift for "+domain)}});
test("startup provides a stable RoomMuse LAN hostname without pinning a stale IP",()=>{const script=readFileSync("scripts/start-roommuse.ps1","utf8"),advertiser=readFileSync("scripts/advertise-roommuse.mjs","utf8"),pkg=JSON.parse(readFileSync("package.json","utf8"));assert.match(script,/\$lanHostName = 'roommuse\.local'/);assert.match(script,/\$friendlyWebUrl = "http:\/\/\$lanHostName`:\$expoPort"/);assert.match(script,/\$stalePrivateIp = \$isPrivateIp -and \$configuredHost -ne \$wifiIp/);assert.match(script,/advertise-roommuse\.mjs/);assert.match(script,/Get-CompatibleNode/);assert.equal(pkg.scripts["lan:name"],"node scripts/advertise-roommuse.mjs");assert.equal(pkg.dependencies["multicast-dns"],"^7.2.5");assert.match(advertiser,/type: "A"/);assert.match(advertiser,/type: "PTR"/);assert.match(advertiser,/type: "SRV"/);assert.match(advertiser,/setInterval\(announce, 60_000\)/)});
