import type{Page}from"@playwright/test";export const roomImage="data:image/svg+xml;utf8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800"><rect width="1200" height="800" fill="#e8e0d2"/><rect x="720" y="90" width="340" height="330" fill="#bfd1d2"/><rect x="110" y="430" width="630" height="210" rx="24" fill="#6b675e"/></svg>');export const report={designDirection:"A room-specific Modern direction organized around the visible window.",layoutAndCirculation:"The seating preserves the visible entry-to-window path.",colorAndMaterials:"Warm neutrals balance the retained floor.",lighting:"The visible window supplies natural light; layered fixtures support evening use.",scaleAndProportion:"All proposed dimensions require field verification.",retainedElements:"Windows, flooring, and openings remain.",priorityChanges:{highestImpact:["Layout"],nextBest:["Lighting"],optional:["Decor"]},designerNotes:["Measure before ordering."]};// A realistic /api/design response. Items look like what the server's live product search returns:
// verified, priced, and linked to a specific retailer product page. The client no longer substitutes
// seeded demo products when this list is short, so the journeys must supply their own.
export const checkedAt="2026-08-16T12:00:00.000Z";
export const shoppingItems=[
  {id:"api-room-0",name:"Fielding performance linen sofa",category:"Furniture",description:"84-inch sofa scaled to the photographed seating wall",quantity:1,unitPrice:1299,retailer:"West Elm",purchaseUrl:"https://www.westelm.com/products/fielding-sofa-h1234/",dimensions:"84 in W x 35 in D",finish:"Performance linen",rationale:"Sized to the visible seating wall and repeats the retained floor tone.",priority:"Essential",isStructurallyImportant:true,availability:"In stock",priceStatus:"verified",lastPriceCheckedAt:checkedAt,budgetTier:"balanced",matchIndicators:["Grounded in photographed living room"],alternatives:[{id:"api-alt-save",name:"Haven compact linen sofa",retailer:"Wayfair",purchaseUrl:"https://www.wayfair.com/furniture/pdp/haven-compact-sofa-w1234.html",unitPrice:899,dimensions:"78 in W x 34 in D",finish:"Woven linen",difference:"Save tier verified product",available:true,availability:"In stock",priceStatus:"verified",lastPriceCheckedAt:checkedAt,budgetTier:"save"}]},
  {id:"api-room-1",name:"Marlow oak floor lamp",category:"Lighting",description:"Task light for the reading corner",quantity:1,unitPrice:219,retailer:"Lamps Plus",purchaseUrl:"https://www.lampsplus.com/p/marlow-oak-floor-lamp-12345/",dimensions:"62 in H",finish:"Aged brass",rationale:"Adds evening task light without blocking the window.",priority:"High impact",availability:"In stock",priceStatus:"verified",lastPriceCheckedAt:checkedAt,budgetTier:"balanced",matchIndicators:["Matches Modern direction"],alternatives:[]}
];
export function apiResponse(partial=false){return{id:"api-signature",title:"Modern Signature",summary:"A room-grounded concept.",style:"Modern",palette:["#ddd","#222","#fafafa"],principles:["Preserve circulation"],beforeImageUrl:roomImage,imageDataUrl:roomImage,shoppingItems:shoppingItems.map(item=>({...item})),designReport:report,roomAnalysis:{roomType:"living room",proportions:"Broad rectangular room",focalPoints:["window"],lighting:"Daylight from the right",retainedElements:["window","flooring"],circulation:"Keep the center path open",confidence:"high"},variants:partial?[]:[{conceptName:"Refined",imageDataUrl:roomImage,designReport:report,generationStatus:"complete"},{conceptName:"Expressive",imageDataUrl:roomImage,designReport:report,generationStatus:"complete"}]}}export async function mockDesign(page:Page,partial=false){await page.route("**/api/design",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(apiResponse(partial))}))}

export async function mockRefine(page:Page){await page.route("**/api/refine",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({imageDataUrl:roomImage,generatedAt:new Date().toISOString(),revisionSummary:"Lighter palette"})}))}
