import {styles as legacyStyles} from "./data";import {Concept,ConceptName,Item,Report,Style} from "./enhancedTypes";
const copy:Record<string,{a:[string,string,string];d:string}>={Modern:{a:["Clean","Warm","Minimal"],d:"Crisp forms, restrained materials, and deliberate contrast."},Contemporary:{a:["Current","Sculptural","Calm"],d:"Soft shapes, refined materials, and an updated editorial feel."},Traditional:{a:["Tailored","Timeless","Layered"],d:"Classic forms, balanced symmetry, and collected detail."},"Mid-Century Modern":{a:["Graphic","Warm","Functional"],d:"Low profiles, natural wood, and iconic geometric forms."},Scandinavian:{a:["Light","Practical","Airy"],d:"Pale woods, soft neutrals, and simple functional comfort."},Japandi:{a:["Serene","Natural","Refined"],d:"Japanese restraint balanced with Scandinavian warmth."},Transitional:{a:["Balanced","Polished","Versatile"],d:"Traditional structure softened by modern simplicity."},Industrial:{a:["Raw","Architectural","Bold"],d:"Metal, wood, texture, and exposed structural character."},"Organic Modern":{a:["Textural","Earthy","Relaxed"],d:"Modern silhouettes softened by natural materials and curves."},Coastal:{a:["Breezy","Natural","Casual"],d:"Light materials, relaxed forms, and an open coastal palette."}};
export const styles:Style[]=legacyStyles.filter(s=>copy[s.name]).map(s=>({...s,attributes:copy[s.name]!.a,description:copy[s.name]!.d}));
const definitions:Record<ConceptName,{d:string;m:string[];l:string}>={Signature:{d:"A balanced interpretation with warm contrast, an open conversation area, and a few sculptural accents.",m:["Natural oak","Ivory linen","Travertine","Aged brass"],l:"A centered seating group anchors the room while keeping the doorway-to-window path open."},Refined:{d:"A quieter direction with lower visual complexity, tonal materials, and timeless silhouettes.",m:["White oak","Oatmeal wool","Matte ceramic","Brushed nickel"],l:"A restrained sofa-and-chair plan leaves more negative space around the room perimeter."},Expressive:{d:"A bolder direction with stronger contrast, curved furniture, and a decorative lighting moment.",m:["Smoked oak","Textured boucle","Veined stone","Patinated brass"],l:"Angled chairs and a rounded table create a dynamic focal group without narrowing circulation."}};
const seeds=[
["paint","Interior wall paint","Finishes","Two gallons, warm soft white",2,59,"The Home Depot","https://www.homedepot.com/s/interior%20paint%20warm%20white","2 gallons","Eggshell","Essential",true],
["sofa","Performance linen sofa","Furniture","84-inch, warm ivory upholstery",1,1299,"Article","https://www.article.com/search?q=ivory%20sofa","84 in W x 35 in D x 31 in H","Performance linen","Essential",true],
["chairs","Oak accent chair","Furniture","Natural oak frame, woven seat",2,329,"West Elm","https://www.westelm.com/search/results.html?words=oak%20accent%20chair","29 in W x 31 in D","Woven seat","High impact",false],
["table","Travertine coffee table","Furniture","Rounded 40-inch profile",1,549,"CB2","https://www.cb2.com/search?query=travertine%20coffee%20table","40 in diameter x 15 in H","Travertine","High impact",false],
["rug","Handwoven wool rug","Textiles","8 x 10 ft, oatmeal",1,489,"Rugs USA","https://www.rugsusa.com/search?q=oatmeal%20wool%20rug","8 x 10 ft","Wool","Essential",true],
["lamp","Linen floor lamp","Lighting","Aged brass with linen shade",1,219,"Lamps Plus","https://www.lampsplus.com/products/?q=linen%20floor%20lamp","62 in H","Aged brass","High impact",false],
["curtains","Linen curtain panels","Textiles","96-inch, natural flax",2,89,"Pottery Barn","https://www.potterybarn.com/search/results.html?words=linen%20curtain","50 in W x 96 in L","Linen","High impact",false],
["art","Textured wall art","Decor","Neutral 36 x 48-inch canvas",1,198,"Etsy","https://www.etsy.com/search?q=neutral%20textured%20wall%20art","36 x 48 in","Textured canvas","Finishing touch",false]
] as const;
const alts=(id:string,p:number)=>[{id:id+"-a",name:"Tailored alternative",retailer:"West Elm",purchaseUrl:"https://www.westelm.com/search/results.html?words=living%20room",unitPrice:Math.max(49,p-120),dimensions:"See retailer dimensions",finish:"Warm neutral",difference:"Lower price"},{id:id+"-b",name:"Compact alternative",retailer:"Article",purchaseUrl:"https://www.article.com/search?q=living%20room",unitPrice:p+40,dimensions:"Compact profile",finish:"Natural finish",difference:"Smaller footprint"},{id:id+"-c",name:"Textural alternative",retailer:"CB2",purchaseUrl:"https://www.cb2.com/search?query=living%20room",unitPrice:p+90,dimensions:"See retailer dimensions",finish:"Textured finish",difference:"Warmer finish"}];
function report(style:Style,name:ConceptName,layout:string):Report{return{designDirection:name+" interprets "+style.name+" with "+definitions[name].d.toLowerCase()+" The palette responds to the photographed room without competing with its openings.",layoutAndCirculation:layout+" The sofa establishes the primary seating wall, with chairs turned inward. A clear walking path remains between the entry and broad window.",colorAndMaterials:"Warm off-white is the primary field, supported by restrained accents. Natural wood, woven wool, linen, and metal add depth while balancing the retained flooring.",lighting:"The window remains the main daylight source. A shaded floor lamp adds task light, a dimmable overhead fixture provides ambient light, and an art light softens the room after dark.",scaleAndProportion:"The 84-inch sofa suits the proposed wall pending a field measurement. An 8 x 10 rug connects the seating. The 40-inch rounded table preserves reach and circulation; 96-inch curtains lift the eye.",retainedElements:"Existing windows, flooring, architectural openings, and room geometry remain. Their positions set the circulation route and keep the window wall open.",priorityChanges:{highestImpact:["Set the warm neutral wall finish","Establish the seating layout","Place the correctly scaled rug"],nextBest:["Layer ambient and task lighting","Install full-height curtains"],optional:["Add artwork","Finish with tactile objects"]},designerNotes:["Keep the window wall open so daylight reaches the seating group.","Center the rug on the conversation area, not the room shell.","Repeat the main wood tone for visual continuity.","Confirm the sofa wall and doorway clearance before ordering."]};}
function items(name:ConceptName,id:string):Item[]{const f=name==="Refined"?.92:name==="Expressive"?1.12:1;return seeds.map((x,i)=>{const p=Math.round(x[5]*f);return{id:id+"-"+x[0],conceptId:id,name:x[1],category:x[2],description:x[3],quantity:x[4],unitPrice:p,retailer:x[6],purchaseUrl:x[7],dimensions:x[8],finish:x[9],priority:x[10],isStructurallyImportant:x[11],rationale:"Selected for its "+x[8]+" scale, "+x[9].toLowerCase()+" finish, and role in the "+name.toLowerCase()+" palette. Confirm field dimensions and current retailer specifications before ordering.",matchIndicators:i<3?["Strong style match","Coordinates with selected palette"]:["Works with retained elements"],availability:"Confirm with retailer",alternatives:alts(x[0],p)};});}
export function concepts(style:Style,before?:string,after?:string):Concept[]{const at=new Date().toISOString();return(["Signature","Refined","Expressive"] as ConceptName[]).map((name,i)=>{const d=definitions[name],id=style.id+"-"+name.toLowerCase()+"-"+Date.now();return{id,conceptId:id,conceptName:name,title:style.name+" "+name,conceptDescription:d.d,summary:d.d,style:style.name,palette:i===2?[style.colors[1],style.colors[0],"#B87958"]:style.colors,materials:d.m,layoutSummary:d.l,principles:[d.l,"Coordinate each material across the room","Layer daylight, task, and ambient lighting"],designReport:report(style,name,d.l),beforeImageUrl:before,imageDataUrl:i===0?after:undefined,shoppingItems:items(name,id),generationStatus:i===0&&after?"complete":"partial",generatedAt:at};});}

