import React,{useState}from"react";
import{Image,Linking,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import*as ImagePicker from"expo-image-picker";
import{SafeAreaView}from"react-native-safe-area-context";
import{applyBudget,selected,total}from"./domain";
import{planTotals}from"./budget";
import type{BudgetTier,Project}from"./enhancedTypes";
import{isDirectProductUrl}from"./productLinks";
import{C}from"./theme";
const money=(n:number)=>"$"+Math.round(n).toLocaleString();
const Btn=({label,onPress,quiet=false}:{label:string;onPress:()=>void;quiet?:boolean})=><Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={[s.btn,quiet&&s.quiet]}><Text style={[s.btnText,quiet&&{color:C.green}]}>{label}</Text></Pressable>;
const Top=({title,back}:{title:string;back:()=>void})=><View style={s.top}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={back} style={s.touch}><Text style={s.back}>‹</Text></Pressable><Text style={s.topTitle}>{title}</Text><View style={s.touch}/></View>;
async function pick(){const r=await ImagePicker.launchImageLibraryAsync({quality:.65,base64:true});const a=r.canceled?undefined:r.assets[0];return a?{uri:a.uri,base64:a.base64??undefined}:undefined}
export function ProjectHub({project,back,open}:{project:Project;back:()=>void;open:(route:"shopping"|"budget"|"field"|"progress"|"deals"|"refresh"|"constraints"|"compare"|"library"|"capture")=>void}){const hub=planTotals(selected(project)!.shoppingItems);const c=selected(project)!;return<SafeAreaView style={s.page}><Top title={project.roomName??c.title} back={back}/><ScrollView contentContainerStyle={s.content}><Image source={{uri:c.imageDataUrl??c.beforeImageUrl??project.sourceImages[0]?.uri}} style={s.hero}/><Text style={s.kicker}>SAVED DECOR · {c.conceptName.toUpperCase()}</Text><Text style={s.h1}>{c.title}</Text><Text style={s.body}>{c.conceptDescription}</Text><View style={s.stats}><Text style={s.stat}>{hub.itemCount} selected items</Text><Text style={s.stat}>{money(hub.remainingToPurchase)} remaining</Text></View><Btn label="View selected shopping list" onPress={()=>open("shopping")}/><Btn label="Choose a budget approach" quiet onPress={()=>open("budget")}/><Btn label="Things to keep" quiet onPress={()=>open("constraints")}/><Btn label="Found something in store" quiet onPress={()=>open("field")}/><Btn label="Compare and favourites" quiet onPress={()=>open("compare")}/><Btn label="Add a project update" quiet onPress={()=>open("progress")}/><Btn label={project.status==="complete"?"View completed prices":"Check for price changes"} quiet onPress={()=>open("refresh")}/><Btn label="Check shopping deals" quiet onPress={()=>open("deals")}/><View style={s.hubDivider}/><Btn label="Your saved projects" quiet onPress={()=>open("library")}/><Btn label="Start a new room" quiet onPress={()=>open("capture")}/><Text style={s.saved}>All photos, list changes, and decisions are saved to this decor project. Starting a new room keeps this one in your saved projects.</Text></ScrollView></SafeAreaView>}
// FieldScreen moved to ShopScreens.tsx in WS-5b: it now identifies the photographed product
// through the vision endpoint and applies a real substitution, rather than emitting a fixed string.
export function ProgressScreen({project,back,save}:{project:Project;back:()=>void;save:(p:Project)=>void}){const[image,setImage]=useState<{uri:string;base64?:string}>(),[note,setNote]=useState("");const add=()=>{if(!image)return;const guidance="You’re making real progress. Finish one visual zone before adding more decor, keep the main walkway clear, and compare the result with your approved image.";save({...project,progressUpdates:[{id:"progress-"+Date.now(),image,note,guidance,createdAt:new Date().toISOString()},...project.progressUpdates],reminders:Array.from(new Set([...project.reminders,"Measure before ordering","Keep receipts until the room is complete"]))});setImage(undefined);setNote("")};return<SafeAreaView style={s.page}><Top title="Project progress" back={back}/><ScrollView contentContainerStyle={s.content}><Text style={s.h1}>Keep the momentum</Text><Text style={s.body}>Share the latest view of your room for encouragement, practical advice, and reminders.</Text>{image&&<Image source={{uri:image.uri}} style={s.upload}/>}<Btn label="Add current room photo" quiet onPress={async()=>setImage(await pick())}/><TextInput accessibilityLabel="Progress note" value={note} onChangeText={setNote} placeholder="What changed, and what are you working on next?" style={s.input}/><Btn label="Save update and get guidance" onPress={add}/>{project.reminders.map(r=><Text key={r} style={s.reminder}>• {r}</Text>)}{project.progressUpdates.map(u=><View key={u.id} style={s.row}><Image source={{uri:u.image.uri}} style={s.thumb}/><View style={{flex:1}}><Text style={s.cardTitle}>{u.note||"Room update"}</Text><Text style={s.body}>{u.guidance}</Text></View></View>)}</ScrollView></SafeAreaView>}
export function DealsScreen({project,back,save}:{project:Project;back:()=>void;save:(p:Project)=>void}){const c=selected(project)!;const check=()=>{const deals=c.shoppingItems.filter(i=>i.priceStatus==="verified"&&!i.isRemoved&&!i.isPurchased&&!i.isOwned).flatMap(i=>(i.alternatives??[]).filter(a=>a.priceStatus==="verified"&&a.lastPriceCheckedAt&&a.unitPrice<i.unitPrice&&isDirectProductUrl(a.purchaseUrl)).map(a=>({id:"deal-"+i.id+"-"+a.id,itemId:i.id,title:a.name,retailer:a.retailer,originalPrice:i.unitPrice,price:a.unitPrice,url:a.purchaseUrl,checkedAt:a.lastPriceCheckedAt!,availability:a.availability,verified:true}))).sort((a,b)=>(a.price/a.originalPrice)-(b.price/b.originalPrice)).slice(0,8);const last=deals.map(d=>d.checkedAt).sort().at(-1);save({...project,deals,lastDealCheckAt:last})};return<SafeAreaView style={s.page}><Top title="Shopping deals" back={back}/><ScrollView contentContainerStyle={s.content}><Text style={s.h1}>Verified savings for this project</Text><Text style={s.body}>Only exact product pages with prices verified when this design was generated appear here. Tracy’s Room Muse never invents a discount. Retailer prices and availability can still change after the checked time.</Text><Btn label="Show verified alternatives" onPress={check}/>{project.lastDealCheckAt&&<Text style={s.saved}>Prices checked {new Date(project.lastDealCheckAt).toLocaleString()}</Text>}{project.deals.length===0&&<Text style={s.saved}>No lower-priced exact product alternatives are currently verified.</Text>}{project.deals.filter(d=>d.verified===true&&isDirectProductUrl(d.url)).map(d=><View key={d.id} style={s.card}><Text style={s.cardTitle}>{d.title}</Text><Text style={s.price}>{money(d.price)} <Text style={s.old}>{money(d.originalPrice)}</Text></Text><Text style={s.body}>{d.retailer}{d.availability?" · "+d.availability:""}</Text><Btn label="View exact product" quiet onPress={()=>Linking.openURL(d.url)}/></View>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.paper},top:{height:56,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:12},touch:{width:44,height:44,alignItems:"center",justifyContent:"center"},back:{fontSize:36,color:C.green},topTitle:{fontWeight:"800",color:C.ink},content:{padding:20,paddingBottom:70},hero:{height:230,borderRadius:24,backgroundColor:"#DDD",marginBottom:18},kicker:{fontSize:10,fontWeight:"800",letterSpacing:1.2,color:C.clay},h1:{fontFamily:"Georgia",fontSize:31,lineHeight:38,color:C.ink,marginVertical:8},body:{fontSize:14,lineHeight:21,color:C.muted},btn:{minHeight:54,borderRadius:17,backgroundColor:C.green,alignItems:"center",justifyContent:"center",marginVertical:5,padding:10},quiet:{backgroundColor:C.paper,borderWidth:1,borderColor:C.line},btnText:{fontSize:15,fontWeight:"800",color:C.white},stats:{flexDirection:"row",gap:8,marginVertical:14},stat:{backgroundColor:"#E8EFE8",padding:9,borderRadius:10,color:C.green,fontWeight:"700"},hubDivider:{height:1,backgroundColor:C.line,marginVertical:14},saved:{fontSize:11,color:C.muted,textAlign:"center",margin:14},card:{padding:17,borderRadius:18,borderWidth:1,borderColor:C.line,marginVertical:7,backgroundColor:C.white},cardOn:{borderWidth:2,borderColor:C.green},cardTitle:{fontSize:16,fontWeight:"800",color:C.ink},price:{fontFamily:"Georgia",fontSize:24,color:C.green,marginTop:5},chosen:{fontWeight:"800",color:C.clay},upload:{height:220,borderRadius:20,marginVertical:10},input:{minHeight:54,borderWidth:1,borderColor:C.line,borderRadius:14,padding:12,backgroundColor:C.white,marginVertical:8},advice:{padding:16,borderRadius:16,backgroundColor:"#E8EFE8",marginVertical:10},row:{flexDirection:"row",gap:12,borderTopWidth:1,borderTopColor:C.line,paddingVertical:14},thumb:{width:82,height:82,borderRadius:12,backgroundColor:"#DDD"},reminder:{padding:10,backgroundColor:"#F5F2EA",marginVertical:3,borderRadius:10,color:C.ink},old:{textDecorationLine:"line-through",color:C.muted,fontSize:15}});
